### ISSUE TITLE
How to use the visualization of mmpretrain in mmfewshot? 

### ISSUE THREAD

**Issue by jianandeng023** [open-mmlab/mmpretrain#1497]
### 描述该功能

Recently I needed to use cam heat maps for my research on mmfewshot, but when I called grad-cam in mmpretrain I got various errors on mmfewshot. I want to provide an interface for mmfewshot to use the mmpretrain visualization tool

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 MMPreTrain 贡献代码！

**Comment by Ezra-Yu** [comment]
I'm very sorry, it's not very easy to implement at the moment. You may need to modify a lot of code and it is recommended to use grad_cam directly instead of based on mmpretrain.

Because mmpretrain and mmfewshot use different versions of mmcv and can't run at the same time, and mmfewshot has no lack of people to maintain no upgrades.

**Comment by Ezra-Yu** [comment]
Just use the `grad_cam` package!
